[tool.poetry]
name = "pytorch_sandbox"
version = "0.1.0"
description = "Playing around with PyTorch"
authors = [ "Benjamin Labrecque" ]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pre-commit = "^3.2.2"
